# Generated by Django 5.1.15 on 2026-07-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotatorprofile',
            name='pay_rate_per_task',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('annotator', 'Annotator'), ('requester', 'Requester'), ('client', 'Client'), ('reviewer', 'Reviewer')], default='annotator', max_length=20),
        ),
    ]
