# Generated by Django 5.1.15 on 2026-07-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_annotatorprofile_pay_rate_per_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_note',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
