# Generated by Django 5.1.15 on 2026-08-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_retired_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='annotate_shortcuts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
