# Generated by Django 5.1.15 on 2026-09-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='verb',
            field=models.CharField(choices=[('team.member_added', 'Team member added'), ('team.member_removed', 'Team member removed'), ('team.role_changed', 'Team role changed'), ('project.team_granted', 'Project access granted to team'), ('project.team_revoked', 'Project access revoked from team'), ('experience.set', 'Experience set'), ('experience.cleared', 'Experience cleared'), ('permission.denied', 'Permission denied'), ('task.claimed', 'Task instance claimed'), ('task.assigned', 'Task instance assigned manually'), ('task.transferred', 'Task instance transferred'), ('task.released', 'Task instance released'), ('task.lease_expired', 'Task instance lease expired'), ('submission.created', 'Submission recorded'), ('submission.superseded', 'Submission superseded'), ('review.recorded', 'Review decision recorded'), ('task.labels_reset', 'Task working labels reset'), ('instance.annotation_set', 'Instance annotation set'), ('instance.annotation_cleared', 'Instance annotation cleared'), ('quality.scored', 'Submission quality scored'), ('milestone.created', 'Milestone created'), ('milestone.updated', 'Milestone updated'), ('milestone.deleted', 'Milestone deleted')], max_length=64),
        ),
    ]
