# Generated by Django 5.1.15 on 2026-07-08 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('annotation_target', models.CharField(default='mitochondria', max_length=100)),
                ('annotation_type', models.CharField(choices=[('semantic_segmentation', 'Semantic segmentation'), ('instance_segmentation', 'Instance segmentation'), ('proofreading', 'Proofreading')], default='instance_segmentation', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('in_annotation', 'In annotation'), ('in_review', 'In review'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
