# Generated by Django 5.1.15 on 2026-07-14 22:43

from django.db import migrations, models

# Backfill map, inlined so the migration stays stable if the choices module
# changes later (annotation_type value -> workflow_type value).
_ANNOTATION_TYPE_TO_WORKFLOW = {
    "semantic_segmentation": "annotation",
    "instance_segmentation": "annotation",
    "proofreading": "proofreading",
}


def backfill_workflow_type(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all().only("id", "annotation_type"):
        workflow = _ANNOTATION_TYPE_TO_WORKFLOW.get(
            project.annotation_type, "annotation"
        )
        Project.objects.filter(pk=project.pk).update(workflow_type=workflow)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_manager_reviewed_project_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workflow_type',
            field=models.CharField(choices=[('annotation', 'Annotation'), ('proofreading', 'Proofreading'), ('segmentation', 'Segmentation')], default='annotation', max_length=20),
        ),
        migrations.RunPython(backfill_workflow_type, migrations.RunPython.noop),
    ]
