# Generated by Django 5.1.15 on 2026-07-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team_teammembership_auditevent_experience_and_more'),
        ('projects', '0005_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='projects', to='accounts.team'),
        ),
    ]
