# Generated by Django 5.1.15 on 2026-07-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
