# Generated by Django 5.1.15 on 2026-08-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_working_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='source',
            field=models.CharField(choices=[('explicit', 'Granted directly'), ('team', 'Mirrored from the working team')], default='explicit', max_length=16),
        ),
    ]
