# Generated by Django 5.1.15 on 2026-09-05 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectmembership_source'),
        ('volumes', '0016_volume_is_gold_standard_volume_reference_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_on', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('met', 'Met'), ('missed', 'Missed')], default='planned', max_length=20)),
                ('target_metric', models.CharField(choices=[('tasks_approved', 'Tasks approved'), ('volumes_completed', 'Volumes completed')], default='tasks_approved', max_length=32)),
                ('target_value', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milestones', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
                ('volumes', models.ManyToManyField(blank=True, related_name='milestones', to='volumes.volume')),
            ],
            options={
                'ordering': ['project_id', 'order', 'due_on', 'id'],
            },
        ),
    ]
