# Generated by Django 5.1.15 on 2026-09-06 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_milestone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
