# Generated by Django 5.1.15 on 2026-07-14 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotation', '0002_remove_annotationtask_payment_amount'),
        ('projects', '0004_project_workflow_type'),
        ('volumes', '0002_volume_chunk_id_volume_source_volume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('inspect', 'Inspect'), ('ingest', 'Ingest'), ('predict', 'Predict'), ('seed', 'Seed'), ('generate_tasks', 'Generate tasks'), ('quality_control', 'Quality control'), ('convert_visualization', 'Convert for visualization'), ('generate_mesh', 'Generate mesh'), ('publish', 'Publish')], max_length=30)),
                ('backend', models.CharField(choices=[('local', 'Local / mock'), ('slurm', 'SLURM')], default='local', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('submitted', 'Submitted'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('external_job_id', models.CharField(blank=True, max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('input_paths', models.JSONField(blank=True, default=dict)),
                ('output_paths', models.JSONField(blank=True, default=dict)),
                ('log_path', models.CharField(blank=True, max_length=1024)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='annotation.annotationtask')),
                ('volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to='volumes.volume')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='processing__status_91c1bf_idx')],
            },
        ),
    ]
