# Generated by Django 5.1.15 on 2026-07-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(choices=[('inspect', 'Inspect'), ('ingest', 'Ingest'), ('predict', 'Predict'), ('seed', 'Seed'), ('generate_tasks', 'Generate tasks'), ('quality_control', 'Quality control'), ('convert_visualization', 'Convert for visualization'), ('generate_mesh', 'Generate mesh'), ('build_pyramid', 'Build pyramid'), ('publish', 'Publish')], max_length=30),
        ),
    ]
