# Generated by Django 5.1.15 on 2026-07-08 22:21

import annotation.models
import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('volumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_start', models.PositiveIntegerField()),
                ('z_end', models.PositiveIntegerField()),
                ('y_start', models.PositiveIntegerField(default=0)),
                ('y_end', models.PositiveIntegerField()),
                ('x_start', models.PositiveIntegerField(default=0)),
                ('x_end', models.PositiveIntegerField()),
                ('task_type', models.CharField(choices=[('manual_annotation', 'Manual annotation'), ('prediction_proofreading', 'Prediction proofreading'), ('final_review', 'Final review'), ('qc_review', 'QC review')], max_length=30)),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision requested')], default='unassigned', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=1)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('instructions', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='volumes.volume')),
            ],
            options={
                'ordering': ['volume_id', 'z_start'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_file', models.FileField(storage=core.storage.get_mito_storage, upload_to=annotation.models.submission_upload_to)),
                ('notes', models.TextField(blank=True)),
                ('qc_status', models.CharField(choices=[('not_run', 'Not run'), ('passed', 'Passed'), ('warning', 'Warning'), ('failed', 'Failed')], default='not_run', max_length=20)),
                ('qc_report', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='annotation.annotationtask')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision requested')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='annotation.annotationsubmission')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
