# Generated by Django 5.1.15 on 2026-07-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationtask',
            name='payment_amount',
        ),
    ]
