# Generated by Django 5.1.15 on 2026-07-21 02:42

import annotation.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_task_priority_difficulty_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationsubmission',
            name='source',
            field=models.CharField(choices=[('upload', 'Uploaded file'), ('inapp', 'In-app editor')], default='upload', max_length=10),
        ),
        migrations.AlterField(
            model_name='annotationsubmission',
            name='label_file',
            field=models.FileField(blank=True, null=True, storage=core.storage.get_mito_storage, upload_to=annotation.models.submission_upload_to),
        ),
    ]
