# Generated by Django 5.1.15 on 2026-07-28 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_default_teams'),
        ('annotation', '0006_submit_lock_and_project_hard_cases'),
        ('projects', '0007_project_paused_project_priority'),
        ('volumes', '0004_backfill_datasets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtask',
            name='pending_instances',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='annotationtask',
            name='total_instances',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_instances', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='annotation.annotationtask')),
            ],
            options={
                'ordering': ['task_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('legacy_kind', models.CharField(choices=[('manual_annotation', 'Manual annotation'), ('prediction_proofreading', 'Prediction proofreading'), ('final_review', 'Final review'), ('qc_review', 'QC review')], default='manual_annotation', max_length=30)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='accounts.institution')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_types', to='accounts.team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='annotationtask',
            name='task_type_ref',
            field=models.ForeignKey(blank=True, help_text='Reusable blueprint. Falls back to the task_type enum when unset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='annotation.tasktype'),
        ),
        migrations.AddConstraint(
            model_name='annotationtask',
            constraint=models.CheckConstraint(condition=models.Q(('pending_instances__gte', 0)), name='pending_instances_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='taskinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_to__isnull', False)), fields=('task', 'assigned_to'), name='uniq_instance_per_task_user'),
        ),
        migrations.AddConstraint(
            model_name='tasktype',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_task_type_name_per_org'),
        ),
    ]
