# Generated by Django 5.1.15 on 2026-07-28 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0008_backfill_task_hierarchy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='claim_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='taskinstance',
            index=models.Index(fields=['state', 'lease_expires_at'], name='idx_instance_lease_sweep'),
        ),
        migrations.AddConstraint(
            model_name='taskinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_to__isnull', False), models.Q(('claim_key', ''), _negated=True)), fields=('assigned_to', 'claim_key'), name='uniq_claim_key_per_user'),
        ),
    ]
