# Generated by Django 5.1.15 on 2026-07-28 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_claim_leases_and_idempotency'),
        ('projects', '0007_project_paused_project_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick_key', models.CharField(help_text="Idempotency handle; a replay returns this row's result.", max_length=128, unique=True)),
                ('mode', models.CharField(choices=[('push', 'Push (applied)'), ('dry_run', 'Dry run (proposed only)')], default='push', max_length=16)),
                ('candidates_considered', models.PositiveIntegerField(default=0)),
                ('users_available', models.PositiveIntegerField(default=0)),
                ('assignments_made', models.PositiveIntegerField(default=0)),
                ('decisions', models.JSONField(blank=True, default=list)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Manager who triggered it; null for an automated tick.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduler_decisions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Set when the run was scoped to one project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_decisions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_sched_decision_recent')],
            },
        ),
    ]
