# Generated by Django 5.1.15 on 2026-07-28 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0010_scheduler_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationsubmission',
            name='superseded_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when a newer submission replaced this one.', null=True),
        ),
        migrations.AddField(
            model_name='annotationsubmission',
            name='supersedes',
            field=models.ForeignKey(blank=True, help_text='The submission this one replaced, forming the round chain.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='annotation.annotationsubmission'),
        ),
        migrations.AddIndex(
            model_name='annotationsubmission',
            index=models.Index(fields=['task', 'superseded_at'], name='idx_submission_current'),
        ),
    ]
