# Generated by Django 5.1.15 on 2026-07-29 05:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0011_submission_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('heartbeats', models.PositiveIntegerField(default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(blank=True, help_text='Set when FEATURE_TASK_HIERARCHY is on; null otherwise.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_sessions', to='annotation.taskinstance')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='annotation.annotationtask')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('paint_slice', 'Paint slice'), ('erase_slice', 'Erase slice'), ('track_slices', 'Track across slices'), ('predict_commit', 'Commit AI prediction'), ('merge_labels', 'Merge labels'), ('split_components', 'Split components'), ('watershed', 'Watershed'), ('undo', 'Undo'), ('redo', 'Redo')], max_length=32)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payload_ref', models.CharField(blank=True, default='', max_length=512)),
                ('payload_digest', models.CharField(blank=True, default='', max_length=64)),
                ('server_ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_ts', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_operations', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='annotation.taskinstance')),
                ('inverse_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inverted_by', to='annotation.annotationoperation')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='annotation.annotationtask')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='annotation.worksession')),
            ],
            options={
                'ordering': ['task_id', 'seq'],
            },
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['actor', 'task'], name='idx_session_actor_task'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['ended_at', 'last_heartbeat_at'], name='idx_session_stale'),
        ),
        migrations.AddConstraint(
            model_name='worksession',
            constraint=models.CheckConstraint(condition=models.Q(('active_seconds__gte', 0)), name='work_session_active_seconds_non_negative'),
        ),
        migrations.AddIndex(
            model_name='annotationoperation',
            index=models.Index(fields=['task', '-seq'], name='idx_operation_recent'),
        ),
        migrations.AddIndex(
            model_name='annotationoperation',
            index=models.Index(fields=['actor', '-server_ts'], name='idx_operation_actor'),
        ),
        migrations.AddConstraint(
            model_name='annotationoperation',
            constraint=models.UniqueConstraint(fields=('task', 'seq'), name='uniq_operation_seq_per_task'),
        ),
        migrations.AddConstraint(
            model_name='annotationoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('task', 'actor', 'idempotency_key'), name='uniq_operation_idempotency_key'),
        ),
    ]
