# Generated by Django 5.1.15 on 2026-08-21 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0020_assignment_transfer_history'),
        ('volumes', '0014_volume_time_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkInterval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, choices=[('ended', 'Client ended the session'), ('idle', 'Idle gap exceeded the timeout'), ('capped', 'Heartbeat gap exceeded the per-interval cap'), ('submitted', 'Task was submitted'), ('expired', 'Abandoned — capped at the last heartbeat'), ('superseded', 'Assignment or permission changed')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['started_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='worksession',
            name='client_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='worksession',
            name='close_reason',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='worksession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['actor', 'task', 'client_token'], name='idx_session_resume'),
        ),
        migrations.AddField(
            model_name='workinterval',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_intervals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workinterval',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='annotation.worksession'),
        ),
        migrations.AddField(
            model_name='workinterval',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_intervals', to='annotation.annotationtask'),
        ),
        migrations.AddField(
            model_name='workinterval',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_intervals', to='volumes.volume'),
        ),
        migrations.AddIndex(
            model_name='workinterval',
            index=models.Index(fields=['actor', 'started_at'], name='idx_interval_actor'),
        ),
        migrations.AddIndex(
            model_name='workinterval',
            index=models.Index(fields=['volume', 'actor'], name='idx_interval_volume'),
        ),
        migrations.AddIndex(
            model_name='workinterval',
            index=models.Index(fields=['task', 'actor'], name='idx_interval_task'),
        ),
        migrations.AddIndex(
            model_name='workinterval',
            index=models.Index(fields=['ended_at'], name='idx_interval_open'),
        ),
    ]
