# Generated by Django 5.1.15 on 2026-08-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0021_work_intervals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardcase',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
