# Generated by Django 5.1.15 on 2026-09-05 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0024_view_location_on_comments_and_hardcases'),
        ('volumes', '0015_time_tracking_rollout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelInstanceAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_id', models.PositiveIntegerField()),
                ('morphology', models.CharField(blank=True, choices=[('normal', 'Normal'), ('elongated', 'Elongated / tubular'), ('fragmented', 'Fragmented / punctate'), ('swollen', 'Swollen'), ('donut', 'Donut / toroidal (MOAS)'), ('mega', 'Megamitochondrion'), ('cristae_loss', 'Cristae disrupted / lost'), ('mitophagy', 'Undergoing mitophagy')], max_length=20)),
                ('qa_flags', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_annotations', to=settings.AUTH_USER_MODEL)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_annotations', to='volumes.volume')),
            ],
            options={
                'ordering': ['volume_id', 'label_id'],
                'indexes': [models.Index(fields=['volume', 'morphology'], name='idx_instance_morphology')],
                'constraints': [models.UniqueConstraint(fields=('volume', 'label_id'), name='uniq_instance_annotation')],
            },
        ),
        migrations.CreateModel(
            name='QualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('gold_standard', 'Scored against a gold-standard reference'), ('reviewer_agreement', "Annotator versus reviewer's approved label")], max_length=32)),
                ('dice', models.FloatField(blank=True, null=True)),
                ('iou', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('instance_f1', models.FloatField(blank=True, help_text='Instances matched at IoU >= 0.5.', null=True)),
                ('false_merges', models.PositiveIntegerField(blank=True, null=True)),
                ('false_splits', models.PositiveIntegerField(blank=True, null=True)),
                ('variation_of_information', models.FloatField(blank=True, null=True)),
                ('provider', models.CharField(max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('reference_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scored_against', to='annotation.annotationsubmission')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_scores', to='annotation.annotationsubmission')),
            ],
            options={
                'ordering': ['-computed_at', '-id'],
                'indexes': [models.Index(fields=['submission', 'kind'], name='idx_quality_sub_kind')],
            },
        ),
    ]
