# Generated by Django 5.1.15 on 2026-09-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0025_labelinstanceannotation_qualityscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityscore',
            name='reference_submission',
        ),
        migrations.RemoveField(
            model_name='qualityscore',
            name='submission',
        ),
        migrations.AddField(
            model_name='hardcase',
            name='category',
            field=models.CharField(blank=True, choices=[('uncertain', 'Uncertain — needs a second opinion'), ('needs_split', 'Under-segmented — one id covers two objects'), ('needs_merge', 'Over-segmented — one object split across ids'), ('false_positive', 'Not a mitochondrion'), ('boundary_truncated', 'Cut off by the volume boundary'), ('other', 'Something else')], max_length=20),
        ),
        migrations.DeleteModel(
            name='LabelInstanceAnnotation',
        ),
        migrations.DeleteModel(
            name='QualityScore',
        ),
    ]
