# Generated by Django 5.1.15 on 2026-07-08 22:21

import core.storage
import volumes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_path', models.CharField(blank=True, max_length=1024)),
                ('image_file', models.FileField(blank=True, null=True, storage=core.storage.get_mito_storage, upload_to=volumes.models.volume_image_upload_to)),
                ('label_path', models.CharField(blank=True, max_length=1024)),
                ('label_file', models.FileField(blank=True, null=True, storage=core.storage.get_mito_storage, upload_to=volumes.models.volume_label_upload_to)),
                ('label_type', models.CharField(choices=[('none', 'No label'), ('prediction', 'Model prediction'), ('proofread', 'Proofread'), ('partial', 'Partial')], default='none', max_length=20)),
                ('shape_z', models.PositiveIntegerField(blank=True, null=True)),
                ('shape_y', models.PositiveIntegerField(blank=True, null=True)),
                ('shape_x', models.PositiveIntegerField(blank=True, null=True)),
                ('voxel_size_z', models.FloatField(blank=True, null=True)),
                ('voxel_size_y', models.FloatField(blank=True, null=True)),
                ('voxel_size_x', models.FloatField(blank=True, null=True)),
                ('file_format', models.CharField(choices=[('tiff', 'TIFF'), ('zarr', 'Zarr'), ('hdf5', 'HDF5'), ('n5', 'N5'), ('other', 'Other')], default='tiff', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('split', 'Split into tasks'), ('in_annotation', 'In annotation'), ('completed', 'Completed')], default='registered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
