# Generated by Django 5.1.15 on 2026-07-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0004_backfill_datasets'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='pyramid_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='volume',
            name='ready_streaming',
            field=models.BooleanField(default=False, help_text='A validated Zarr v3 pyramid exists for this volume. Flipped only after random-chunk checksums pass (doc 20 §Pyramid job).'),
        ),
    ]
