# Generated by Django 5.1.15 on 2026-08-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    """Drop the legacy ``split`` volume status.

    A volume is one assignable unit, so "Split into tasks" was only ever set by
    the removed frame-splitting service. This is a choices-only ``AlterField``:
    the column stays ``varchar(20)`` and no row is touched. Both the deployment
    and development databases were verified to hold zero ``status='split'``
    rows before this was written.
    """

    dependencies = [
        ('volumes', '0009_volume_region_pyramid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('in_annotation', 'In annotation'), ('completed', 'Completed')], default='registered', max_length=20),
        ),
    ]
