# Generated by Django 5.1.15 on 2026-08-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0013_pin_working_mask_basename'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='time_tracking',
            field=models.CharField(choices=[('eligible', 'Time tracking eligible'), ('legacy_exempt', 'Legacy — annotation time unknown')], db_index=True, default='eligible', help_text="Whether annotation time is measured for this volume. Legacy-exempt volumes always report '-', never zero.", max_length=20),
        ),
        migrations.AddField(
            model_name='volume',
            name='time_tracking_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='volume',
            name='time_tracking_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
