# Generated by Django 5.1.15 on 2026-09-05 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0025_labelinstanceannotation_qualityscore'),
        ('volumes', '0015_time_tracking_rollout'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='is_gold_standard',
            field=models.BooleanField(default=False, help_text='Submissions on this volume are scored against ``reference_submission``.'),
        ),
        migrations.AddField(
            model_name='volume',
            name='reference_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_standard_for', to='annotation.annotationsubmission'),
        ),
    ]
