# Generated by Django 5.1.15 on 2026-09-06 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volumes', '0016_volume_is_gold_standard_volume_reference_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='is_gold_standard',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='reference_submission',
        ),
    ]
